name: Aggregate feeds (hourly)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # every hour, UTC
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Fetch & build
        run: python scripts/fetch_and_build.py
      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/data/items.json
          git diff --staged --quiet || (git commit -m "update items.json" && git push)
